---

include:
  - project: 'saltbox/ci-lib'
    file: 'build-image.yml'

  - project: 'saltbox/ci-lib'
    file: 'def-branch-merge-guard.yml'


stages:
  - build
  - test


Build Frontend Metric image:
  extends: .build-image
  stage: test
